"""Reconstrucao

Revision ID: 55be0befdaf9
Revises: 
Create Date: 2026-03-22 18:53:31.848863

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55be0befdaf9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categorias',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('nome')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=True),
    sa.Column('sobrenome', sa.String(length=100), nullable=True),
    sa.Column('cpf', sa.String(length=14), nullable=True),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('telefone', sa.String(length=15), nullable=True),
    sa.Column('perfil', sa.String(length=20), nullable=False),
    sa.Column('logradouro', sa.String(length=254), nullable=True),
    sa.Column('bairro', sa.String(length=100), nullable=True),
    sa.Column('cidade', sa.String(length=100), nullable=True),
    sa.Column('estado', sa.String(length=2), nullable=True),
    sa.Column('numero', sa.String(length=10), nullable=True),
    sa.Column('sem_numero', sa.Boolean(), nullable=True),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('ponto_referencia', sa.String(length=100), nullable=True),
    sa.Column('etapa_registro', sa.String(length=50), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('telefone')
    )
    op.create_table('restaurantes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome_fantasia', sa.String(length=50), nullable=False),
    sa.Column('razao_social', sa.String(length=255), nullable=False),
    sa.Column('cnpj', sa.String(length=14), nullable=False),
    sa.Column('logotipo', sa.String(length=255), nullable=True),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('categoria_id', sa.Integer(), nullable=True),
    sa.Column('endereco', sa.String(length=254), nullable=False),
    sa.Column('complemento', sa.String(length=100), nullable=True),
    sa.Column('telefone', sa.String(length=11), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cnpj'),
    sa.UniqueConstraint('email')
    )
    op.create_table('horarios_funcionamento',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('dia_semana', sa.Integer(), nullable=False),
    sa.Column('abertura', sa.Time(), nullable=False),
    sa.Column('fechamento', sa.Time(), nullable=False),
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('otp_codes',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=6), nullable=True),
    sa.Column('link_token', sa.String(length=100), nullable=True),
    sa.Column('data_expiracao', sa.DateTime(), nullable=False),
    sa.Column('tentativas', sa.Integer(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=True),
    sa.Column('restaurante_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('link_token')
    )
    op.create_table('produtos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('descricao', sa.String(length=500), nullable=True),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('imagem', sa.String(length=255), nullable=True),
    sa.Column('disponivel', sa.Boolean(), nullable=False),
    sa.Column('categoria_id', sa.Integer(), nullable=False),
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['categoria_id'], ['categorias.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('grupos_adicionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('min_quantidade', sa.Integer(), nullable=False),
    sa.Column('max_quantidade', sa.Integer(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('adicionais',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('preco', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('grupo_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['grupo_id'], ['grupos_adicionais.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('adicionais')
    op.drop_table('grupos_adicionais')
    op.drop_table('produtos')
    op.drop_table('otp_codes')
    op.drop_table('horarios_funcionamento')
    op.drop_table('restaurantes')
    op.drop_table('usuarios')
    op.drop_table('categorias')
    # ### end Alembic commands ###
