"""add_cart_cupom_pedido_minimo

Revision ID: 55db9e731274
Revises: b3c4d5e6f7a8
Create Date: 2026-04-25 21:02:50.740975

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55db9e731274'
down_revision = 'b3c4d5e6f7a8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cupons',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('codigo', sa.String(length=50), nullable=False),
    sa.Column('tipo', sa.String(length=10), nullable=False),
    sa.Column('valor', sa.Integer(), nullable=False),
    sa.Column('valor_minimo_centavos', sa.Integer(), nullable=False),
    sa.Column('ativo', sa.Boolean(), nullable=False),
    sa.Column('data_expiracao', sa.DateTime(), nullable=True),
    sa.Column('usos_maximos', sa.Integer(), nullable=True),
    sa.Column('usos_atuais', sa.Integer(), nullable=False),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('codigo')
    )
    op.create_table('carrinhos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('congelado', sa.Boolean(), nullable=False),
    sa.Column('token_checkout', sa.String(length=36), nullable=True),
    sa.Column('cupom_id', sa.Integer(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['cupom_id'], ['cupons.id'], ),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token_checkout'),
    sa.UniqueConstraint('usuario_id')
    )
    op.create_table('itens_carrinho',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('carrinho_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario_centavos', sa.Integer(), nullable=False),
    sa.Column('observacao', sa.String(length=200), nullable=True),
    sa.ForeignKeyConstraint(['carrinho_id'], ['carrinhos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_adicionais_carrinho',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('item_id', sa.UUID(), nullable=False),
    sa.Column('adicional_id', sa.Integer(), nullable=False),
    sa.Column('nome_adicional', sa.String(length=100), nullable=False),
    sa.Column('preco_centavos', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adicional_id'], ['adicionais.id'], ),
    sa.ForeignKeyConstraint(['item_id'], ['itens_carrinho.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pedido_minimo_centavos', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_column('pedido_minimo_centavos')

    op.drop_table('itens_adicionais_carrinho')
    op.drop_table('itens_carrinho')
    op.drop_table('carrinhos')
    op.drop_table('cupons')
    # ### end Alembic commands ###
