"""refatorar_adicionais_globais

Revision ID: 6c2f8af51dfa
Revises: 7e0bb38d1de0
Create Date: 2026-05-31 23:27:41.110229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c2f8af51dfa'
down_revision = '7e0bb38d1de0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('produto_adicionais',
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('adicional_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['adicional_id'], ['adicionais.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('produto_id', 'adicional_id')
    )
    # moved op.drop_table to bottom
    with op.batch_alter_table('adicionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade_atual', sa.Numeric(precision=10, scale=3), nullable=False))
        batch_op.add_column(sa.Column('restaurante_id', sa.UUID(), nullable=False))
        batch_op.drop_constraint(batch_op.f('adicionais_grupo_id_fkey'), type_='foreignkey')
        batch_op.create_foreign_key(None, 'restaurantes', ['restaurante_id'], ['id'])
        batch_op.drop_column('grupo_id')
        batch_op.drop_column('disponivel')

    op.drop_table('grupos_adicionais')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adicionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disponivel', sa.BOOLEAN(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('grupo_id', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(batch_op.f('adicionais_grupo_id_fkey'), 'grupos_adicionais', ['grupo_id'], ['id'])
        batch_op.drop_column('restaurante_id')
        batch_op.drop_column('quantidade_atual')

    op.create_table('grupos_adicionais',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('nome', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('produto_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('min_selecao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('max_selecao', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('obrigatorio', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], name=op.f('grupos_adicionais_produto_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('grupos_adicionais_pkey'))
    )
    op.drop_table('produto_adicionais')
    # ### end Alembic commands ###
