"""add_ingredientes_e_ficha_tecnica

Revision ID: 7e0bb38d1de0
Revises: a64e93258734
Create Date: 2026-05-31 22:36:54.429201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0bb38d1de0'
down_revision = 'a64e93258734'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ingredientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('nome', sa.String(length=100), nullable=False),
    sa.Column('quantidade_atual', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unidade_medida', sa.String(length=10), nullable=False),
    sa.Column('custo_unitario', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('produto_ingredientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=False),
    sa.Column('ingrediente_id', sa.UUID(), nullable=False),
    sa.Column('quantidade_necessaria', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.ForeignKeyConstraint(['ingrediente_id'], ['ingredientes.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('produto_ingredientes')
    op.drop_table('ingredientes')
    # ### end Alembic commands ###
