"""add quantidade to produtos — modulo estoque RF-01

Revision ID: a64e93258734
Revises: d106cbbf1677
Create Date: 2026-05-31 22:16:33.302234

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a64e93258734'
down_revision = 'd106cbbf1677'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantidade', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('produtos', schema=None) as batch_op:
        batch_op.drop_column('quantidade')

    # ### end Alembic commands ###
