"""add pedidos table

Revision ID: d106cbbf1677
Revises: 55db9e731274
Create Date: 2026-04-27 22:33:08.187629

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'd106cbbf1677'
down_revision = '55db9e731274'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cartoes_clientes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('mp_customer_id', sa.String(length=100), nullable=False),
    sa.Column('mp_card_id', sa.String(length=100), nullable=False),
    sa.Column('ultimos_digitos', sa.String(length=4), nullable=True),
    sa.Column('bandeira', sa.String(length=50), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pedidos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('usuario_id', sa.UUID(), nullable=False),
    sa.Column('restaurante_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=False),
    sa.Column('troco_para_centavos', sa.Integer(), nullable=True),
    sa.Column('subtotal_centavos', sa.Integer(), nullable=False),
    sa.Column('taxa_entrega_centavos', sa.Integer(), nullable=False),
    sa.Column('desconto_centavos', sa.Integer(), nullable=False),
    sa.Column('total_centavos', sa.Integer(), nullable=False),
    sa.Column('cupom_codigo', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.String(length=140), nullable=True),
    sa.Column('endereco_entrega_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['restaurante_id'], ['restaurantes.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('itens_pedido',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('produto_id', sa.UUID(), nullable=True),
    sa.Column('nome_produto', sa.String(length=255), nullable=False),
    sa.Column('quantidade', sa.Integer(), nullable=False),
    sa.Column('preco_unitario_base_centavos', sa.Integer(), nullable=False),
    sa.Column('preco_total_item_centavos', sa.Integer(), nullable=False),
    sa.Column('adicionais', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.ForeignKeyConstraint(['produto_id'], ['produtos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('pedido_id', sa.UUID(), nullable=False),
    sa.Column('mercado_pago_id', sa.BIGINT(), nullable=True),
    sa.Column('metodo', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('valor_centavos', sa.Integer(), nullable=False),
    sa.Column('pix_qr_code', sa.Text(), nullable=True),
    sa.Column('pix_qr_code_base64', sa.Text(), nullable=True),
    sa.Column('data_criacao', sa.DateTime(), nullable=False),
    sa.Column('data_atualizacao', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['pedido_id'], ['pedidos.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('mercado_pago_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pagamentos')
    op.drop_table('itens_pedido')
    op.drop_table('pedidos')
    op.drop_table('cartoes_clientes')
    # ### end Alembic commands ###
