"""Add capa to restaurantes

Revision ID: f6aeb541c077
Revises: 55be0befdaf9
Create Date: 2026-03-30 22:04:25.754488

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f6aeb541c077'
down_revision = '55be0befdaf9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('adicionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('disponivel', sa.Boolean(), nullable=False))

    with op.batch_alter_table('grupos_adicionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_selecao', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('max_selecao', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('obrigatorio', sa.Boolean(), nullable=False))
        batch_op.drop_column('max_quantidade')
        batch_op.drop_column('min_quantidade')

    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('capa', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('restaurantes', schema=None) as batch_op:
        batch_op.drop_column('capa')

    with op.batch_alter_table('grupos_adicionais', schema=None) as batch_op:
        batch_op.add_column(sa.Column('min_quantidade', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.add_column(sa.Column('max_quantidade', sa.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('obrigatorio')
        batch_op.drop_column('max_selecao')
        batch_op.drop_column('min_selecao')

    with op.batch_alter_table('adicionais', schema=None) as batch_op:
        batch_op.drop_column('disponivel')

    # ### end Alembic commands ###
